# -*- coding: utf-8 -*-
"""Decipher_Test_recommendation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p9q3CBiIu4XfePpwx9qUBEhPRsMlFTC3
"""

#Importing the necessary libraries
import json
import numpy as np
import pandas as pd

#Reading the json file's
import json

with open('/content/drive/My Drive/students.json') as f:
  data = json.load(f)

with open('/content/drive/My Drive/tests_details.json') as f:
  test_details = json.load(f)


with open('/content/drive/My Drive/test_submissions.json') as f:
  test_submission = json.load(f)

Different_super_groups=[]  # A list to contain all the different supergroups

# To find all the different supergroups in which students are enrolled
for i in range(0,10000):
  try:
    for k in data[i]['target_super_groups']:
      Different_super_groups.append(k['title'][0]['value'])
  except:
    continue

# To print only the unique elements of a list
def unique(list1): 
    x = np.array(list1) 
    print(np.unique(x))

unique(Different_super_groups) # The Different supergroups we have

#Different lists to store the students enrolled in different supergroups
Defence_Exams=[]
Engineering_Recruitment_Exams=[]
Insurance_Exams=[]
Other_Govt_Exams=[]
Police_Exams=[]
Professional_Skills=[]
Railways_Exams=[]
SSC_Exams=[]
State_Govt_Exams=[]
Teaching_Exams=[]
Banking_Exams=[]

# If else condition to appends the students in the list in which supergoup they are enrolled
for i in range(0,10000):
  try:
    for k in data[i]['target_super_groups']:
      if(k['title'][0]['value']== 'Banking Exams'):
        Banking_Exams.append(data[i]['sid'])
      if(k['title'][0]['value']== 'Defence Exams'):
        Defence_Exams.append(data[i]['sid'])
      if(k['title'][0]['value']== 'Engineering Recruitment Exams'):
        Engineering_Recruitment_Exams.append(data[i]['sid'])
      if(k['title'][0]['value']== 'Insurance Exams'):
        Insurance_Exams.append(data[i]['sid'])
      if(k['title'][0]['value']== 'Other Govt. Exams'):
        Other_Govt_Exams.append(data[i]['sid'])
      if(k['title'][0]['value']== 'Police Exams'):
        Police_Exams.append(data[i]['sid'])
      if(k['title'][0]['value']== 'Professional Skills'):
        Professional_Skills.append(data[i]['sid'])
      if(k['title'][0]['value']== 'Railways Exams'):
        Railways_Exams.append(data[i]['sid'])
      if(k['title'][0]['value']== 'SSC Exams'):
        SSC_Exams.append(data[i]['sid'])
      if(k['title'][0]['value']== 'State Govt. Exams'):
        State_Govt_Exams.append(data[i]['sid'])
      if(k['title'][0]['value']== 'Teaching Exams'):
        Teaching_Exams.append(data[i]['sid'])
  except:
    continue

# List to store all the tests to the supergroup for which they are for
Defence_Exams_test=[]
Engineering_Recruitment_Exams_test=[]
Insurance_Exams_test=[]
Other_Govt_Exams_test=[]
Police_Exams_test=[]
Professional_Skills_test=[]
Railways_Exams_test=[]
SSC_Exams_test=[]
State_Govt_Exams_test=[]
Teaching_Exams_test=[]
Banking_Exams_test=[]

# As we found for many tests their Super target group was null so we manually found out the the super target group for each target and appended them in the list.

for i in range(0,876):
  try:
    exam=test_details[i]['target'][0]['title'][0]['value']
    if exam=='AFCAT' or exam=="AMCAT" or exam == 'Airforce Group X' or exam == 'Airforce Group Y' or exam== 'CDS' or exam == 'CISF Constable' or exam == 'DRDO MTS' or exam=='Navy AA' or exam =='Navy SSR' or exam == 'Navy MR' or exam =='NDA':
      Defence_Exams_test.append(test_details[i]['test_id'])
    if exam =='AP Police Constable' or exam == 'Bihar Police ASI Steno' or exam =='Bihar Police Constable' or exam == 'Bihar Police SI' or exam == 'Rajasthan Police Constable' or exam=='Bihar Police Forest Guard' or exam == 'Delhi Police Constable' or exam == 'Delhi Police Head Constable' or exam =='Haryana Police Constable' or exam=='MP Jail Prahari' or exam=='UP Police Constable' or exam=='UP Police Jail Warder' or exam=='UP Police Sub Inspector' or exam=='UPSC CAPF AC':
      Police_Exams_test.append(test_details[i]['test_id'])
    if exam=='APSC Assistant Engineer' or exam == 'ECIL CS' or exam =='GATE CE' or exam =='GATE EC' or exam=='GATE CS' or exam=='GATE EE' or exam=='GATE ME' or exam=='ISRO Scientist CS' or exam =='ISRO Scientist EC' or exam =='ISRO Technical Assistant' or exam=='ISRO Technician' or exam=='MPTET' or exam=='RCFL' or exam=='NLC Graduate Executive Trainee' or exam=='rcfl' or exam=='TCS' or exam=='UPPCL Assistant Engineer' or exam=='UPPSC AE' or exam=='UPRVUNL AE' or exam=='Vizag Steel Management Trainee' or exam=='UPSC IES':
      Engineering_Recruitment_Exams_test.append(test_details[i]['test_id'])
    if exam =='CTET' or exam=='Bihar STET' or exam=='REET' or exam=='TN TRB CS' or exam=='UGC NET':
      Teaching_Exams_test.append(test_details[i]['test_id'])
    if exam=='Bank of Baroda PO' or exam== 'IBPS SO' or exam=='IBPS Clerk' or exam=='IBPS PO' or exam =='J&K Bank Clerk' or exam== 'RBI Assistant' or exam== 'RBI Grade B' or exam =='RRB Officer Scale - I' or exam=='RRC Group D' or exam=='SBI Clerk' or exam =='SBI PO' or exam =='SBI SO' or exam=='SEBI Grade A':
      Banking_Exams_test.append(test_details[i]['test_id'])
    if exam == 'CWC Junior Superintendent' or exam=='FCI Manager' or exam=='NBE':
      Other_Govt_Exams_test.append(test_details[i]['test_id'])
    if exam == 'Current Affairs' or exam =='English' or exam=='Skill Courses':
      Professional_Skills_test.append(test_details[i]['test_id'])
    if exam ==  'DDA Patwari' or exam == 'DSSSB' or exam=='HSSC Group D' or exam== 'MP Patwari' or exam=='REET' or exam=='RRB Office Assistant' or exam=='RRC Group D' or exam=='RSMSSB JE' or exam=='Rajasthan Patwari' or exam=='UP Lekhpal' or  exam=='UPPCL Technician' or exam=='UPPCS':
      State_Govt_Exams_test.append(test_details[i]['test_id'])
    if exam=='DMRC Maintainer' or exam=='RRB ALP' or exam=='RRB NTPC' or exam=='RRB JE':
      Railways_Exams_test.append(test_details[i]['test_id'])
    if exam =='LIC AAO' or exam == 'LIC Assistant' or exam=='NIACL AO' or exam=='UPSC EPFO':
      Insurance_Exams_test.append(test_details[i]['test_id'])
    if exam == 'IT Officer - Scale I' or exam=='SSC CGL' or exam=='SSC CHSL' or exam=='SSC CPO' or exam=='SSC GD Constable' or exam=='SSC JE CE' or exam=='SSC JE EE' or exam== 'SSC JE ME'or exam=='SSC JHT' or exam=='SSC MTS' or exam=='SSC Selection Post' or exam=='SSC Stenographer':
      SSC_Exams_test.append(test_details[i]['test_id'])
  except:
    continue

All_tests=[]  #A list to store all the tests

for i in range(0,876):
  All_tests.append(test_details[i]['test_id'])

test_taken=[] #A list to store all the tests that were previously taken by the students

# To store the test taken in the list
for i in range(0,3589):
  try:
     test_taken.append(test_submission[i]['testId'])
  except:
     continue

#A list to count how many times each test was previously taken for each super target group
Defence_course_count=[]
Engineering_Recruitment_course_count=[]
Insurance_course_count=[]
Other_Govt_course_count=[]
Police_course_count=[]
Professional_Skills_course_count=[]
Railways_course_count=[]
SSC_course_count=[]
State_Govt_course_count=[]
Teaching_course_count=[]
Banking_course_count=[]

All_tests_count=[]  #To count number of times all the tests that are previously taken

# To count number of times each test has been taken to set the priority
for j in Defence_Exams_test:
  Defence_course_count.append(test_taken.count(j))

for j in Engineering_Recruitment_Exams_test:
  Engineering_Recruitment_course_count.append(test_taken.count(j))

for j in Insurance_Exams_test:
  Insurance_course_count.append(test_taken.count(j))

for j in Other_Govt_Exams_test:
  Other_Govt_course_count.append(test_taken.count(j))

for j in Police_Exams_test:
  Police_course_count.append(test_taken.count(j))                                 

for j in Professional_Skills_test:
  Professional_Skills_course_count.append(test_taken.count(j))

for j in Railways_Exams_test:
  Railways_course_count.append(test_taken.count(j))

for j in SSC_Exams_test:
  SSC_course_count.append(test_taken.count(j))

for j in State_Govt_Exams_test:
  State_Govt_course_count.append(test_taken.count(j))


for j in Teaching_Exams_test:
  Teaching_course_count.append(test_taken.count(j))

for j in Banking_Exams_test:
  Banking_course_count.append(test_taken.count(j))

for j in All_tests:
  All_tests_count.append(test_taken.count(j))

# To create a dataframe with the test-Id and their count to set the priority
Defence_Exams_test = pd.DataFrame({'All_courses':Defence_Exams_test,'Count':Defence_course_count})
Engineering_Recruitment_Exams_test = pd.DataFrame({'All_courses':Engineering_Recruitment_Exams_test,'Count':Engineering_Recruitment_course_count})
Insurance_Exams_test = pd.DataFrame({'All_courses':Insurance_Exams_test,'Count':Insurance_course_count})
Other_Govt_Exams_test = pd.DataFrame({'All_courses':Other_Govt_Exams_test,'Count':Other_Govt_course_count})
Police_Exams_test = pd.DataFrame({'All_courses':Police_Exams_test,'Count':Police_course_count})
Professional_Skills_test = pd.DataFrame({'All_courses':Professional_Skills_test,'Count':Professional_Skills_course_count})
Railways_Exams_test= pd.DataFrame({'All_courses':Railways_Exams_test,'Count':Railways_course_count})
SSC_Exams_test = pd.DataFrame({'All_courses':SSC_Exams_test,'Count':SSC_course_count})
State_Govt_Exams_test = pd.DataFrame({'All_courses':State_Govt_Exams_test,'Count':State_Govt_course_count})
Teaching_Exams_test = pd.DataFrame({'All_courses':Teaching_Exams_test,'Count':Teaching_course_count})
Banking_Exams_test = pd.DataFrame({'All_courses':Banking_Exams_test,'Count':Banking_course_count})
All_tests = pd.DataFrame({'All_courses':All_tests,'Count': All_tests_count})

# To sort them on the basis of their previous occurance

Defence_Exams_test =Defence_Exams_test.sort_values(by ='Count', ascending=False, inplace=False)
Engineering_Recruitment_Exams_test = Engineering_Recruitment_Exams_test.sort_values(by ='Count', ascending=False, inplace=False)
Insurance_Exams_test = Insurance_Exams_test.sort_values(by ='Count', ascending=False, inplace=False)
Other_Govt_Exams_test = Other_Govt_Exams_test.sort_values(by ='Count', ascending=False, inplace=False)
Police_Exams_test  = Police_Exams_test.sort_values(by ='Count', ascending=False, inplace=False)
Professional_Skills_test= Professional_Skills_test.sort_values(by ='Count', ascending=False, inplace=False)
Railways_Exams_test    = Railways_Exams_test.sort_values(by ='Count', ascending=False, inplace=False)
SSC_Exams_test     = SSC_Exams_test.sort_values(by ='Count', ascending=False, inplace=False)
State_Govt_Exams_test= State_Govt_Exams_test.sort_values(by ='Count', ascending=False, inplace=False)
Teaching_Exams_test  = Teaching_Exams_test.sort_values(by ='Count', ascending=False, inplace=False)
Banking_Exams_test = Banking_Exams_test.sort_values(by ='Count', ascending=False, inplace=False)

All_tests = All_tests.sort_values(by ='Count', ascending=False, inplace=False)

#Function to recommend the test
def result():
  query=input()
  m=0
  Recommendation=[]
  m=[] 
  for i in range(0,3589):
    if test_submission[i]['studentId'] == query:
      if test_submission[i]['correct'] >= 1 and test_submission[i]['correct'] < 25:
        Recommendation.append(test_submission[i]['testId'])
  if query in Banking_Exams:
    index = Banking_Exams_test.index
    number_of_rows = len(index)
    for i in range(0,number_of_rows):
      if Banking_Exams_test.iloc[i,0] not in m:
        Recommendation.append(Banking_Exams_test.iloc[i,0])
        break;
  if query in Defence_Exams:
    index = Defence_Exams_test.index
    number_of_rows = len(index)
    for i in range(0,number_of_rows):
      if Defence_Exams_test.iloc[i,0] not in m:
        Recommendation.append(Defence_Exams_test.iloc[i,0])
        break;
  if query in Engineering_Recruitment_Exams:
    index = Engineering_Recruitment_Exams_test.index
    number_of_rows = len(index)
    for i in range(0,number_of_rows):
      if Engineering_Recruitment_Exams_test.iloc[i,0] not in m:
        Recommendation.append(Engineering_Recruitment_Exams_test.iloc[i,0])
        break;
  if query in Insurance_Exams:
    index = Insurance_Exams_test.index
    number_of_rows = len(index)
    for i in range(0,number_of_rows):
      if Insurance_Exams_test.iloc[i,0] not in m:
        Recommendation.append(Insurance_Exams_test.iloc[i,0])
        break;
  if query in Police_Exams:
    index = Police_Exams_test.index
    number_of_rows = len(index)
    for i in range(0,number_of_rows):
      if Police_Exams_test.iloc[i,0] not in m:
        Recommendation.append(Police_Exams_test.iloc[i,0])
        break;
  if query in Professional_Skills:
    index = Professional_Skills_test.index
    number_of_rows = len(index)
    for i in range(0,number_of_rows):
      if Professional_Skills_test.iloc[i,0] not in m:
        Recommendation.append(Professional_Skills_test.iloc[i,0])
        break;
  if query in Railways_Exams:
    index = Railways_Exams_test.index
    number_of_rows = len(index)
    for i in range(0,number_of_rows):
      if Railways_Exams_test.iloc[i,0] not in m:
        Recommendation.append(Railways_Exams_test.iloc[i,0])
        break;
  
  if query in SSC_Exams:
    index = SSC_Exams_test.index
    number_of_rows = len(index)
    for i in range(0,number_of_rows):
      if SSC_Exams_test.iloc[i,0] not in m:
        Recommendation.append(SSC_Exams_test.iloc[i,0])
        break;
  if query in State_Govt_Exams:
    index = State_Govt_Exams_test.index
    number_of_rows = len(index)
    for i in range(0,number_of_rows):
      if State_Govt_Exams_test.iloc[i,0] not in m:
        Recommendation.append(State_Govt_Exams_test.iloc[i,0])
        break;
  if len(Recommendation)==0:
     index = All_tests.index
     number_of_rows = len(index)
     for i in range(0,number_of_rows):
       if All_tests.iloc[i,0] not in m:
         Recommendation.append(All_tests.iloc[i,0])
         break;
  print("The recommended Tests are\n")
  unique(Recommendation)

result()

"""The Student with Sid-"15124e459c173f28a53b4863fdb8f6b3" is enrolled for preparation of Banking, Railways and SSC exams so The test "dfb896ae1ed198daa72758980ddc4efe" is recommended because this test is taken by maximum number of students that is 368 students who are enrolled for Banking exams preparation similary test "b4ca204631b17b6b486c361872fd2af2" and "82e37348498073236bf7fbd32191bf3e" is recommended because he is enrolled for SSC and Railways Preparation and these tests were take by 94 , 94 students respectively which is maximum and the test "a82e3ddc77d28b3ef773e1228dd13d12" is recommended because the student has previously enrolled for this test and got 2 marks in that and we think there is a chance of improvement if student appear again for the same test, But we have not recommended him the other test in which he is appeared previously that is "dcf403b70447d14bdfc2a922452abddd" because he has not corrected a single question of the test so we dont't think he is ready for this test now."""

result()

"""The student with Sid-"a341f4641772b42ffb04b74522734d84" has already appeard in the test "a8d11a82ba438ea1dda0661e6a791de0" but we have not recommended him that test because he have scored 38 in the test which is better compared to other's so we have recommended him other tests of the super target group in which he is enrolled that are Banking,Defence and police exams preparation,The test we have recommended are the most frequent tests taken are by the students who are enrolled in these super target groups."""